kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-extra
  namespace: poc-developer-hub
immutable: false
data:
  app-config-extra.yaml: |
    app:
      title: Developer Hub - Poc - v0.2
      baseUrl: https://backstage-community-poc-developer-hub.apps.k8s.dev.local
