kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-extra
  namespace: poc-developer-hub
immutable: false
data:
  app-config-extra.yaml: |
    app:
      title: Developer Hub - Poc - v0.2
      baseUrl: https://backstage-community-poc-developer-hub.apps.k8s.dev.local
    backend:
      auth:
        externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: "pl4s3Ch4ng3M3"
      baseUrl: https://backstage-community-poc-developer-hub.apps.k8s.dev.local
      cors:
        origin: https://backstage-community-poc-developer-hub.apps.k8s.dev.local
