apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cristiano-pires-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:15.8-alpine3.20
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pg-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
              subPath: data
          securityContext:
            runAsUser: 70        # UID do postgres
            runAsGroup: 70       # GID do postgres
            fsGroup: 70          # GID que permitirá acesso ao diretório
      volumes:
        - name: postgresdb
          #persistentVolumeClaim:
          #  claimName: pg-storage-claim
          emptyDir: {}