apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: cristiano-pires-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: quay.io/janus-idp/backstage-showcase:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          command: [ "node", "packages/backend", "--no-node-snapshot", "--config", "app-config.yaml" ]  # Substitui o ENTRYPOINT
          args:
            - "--config"
            - "app-config.yaml"
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
# Uncomment if health checks are enabled in your app:
# https://backstage.io/docs/plugins/observability#health-checks
#          readinessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
#          livenessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck